### ISSUE TITLE
Voltage Sensor Always Zero

### ISSUE THREAD

**Issue by kyleparry192** [gndean/home-assistant-hypervolt-charger#18]
Hey,

I'm testing this out on a Hypervolt 3.0 charger and it looks like the `current_voltage_session` is always zero, even during a charging session.

**Comment by kyleparry192** [comment]
I've done some further investigation an it looks like this value is always 0 in the API response.

 {"charging":true,"session":0,"milli_amps":0,"true_milli_amps":6100,"watt_hours":87452,"ccy_spent":0,"carbon_saved_grams":38216,"ct_current":0,"ct_power":0,"voltage":0}

**Comment by gndean** [comment]
A belated acknowledgment to this. I'm guessing this is a feature not supported by the 3.0 charger. I'll add a comment to the readme next time I change it to note this.

If anyone else reading this has a 3.0 charger and can confirm if they see the same issue, that would be helpful to know. Thanks.

**Comment by gndean** [comment]
I've updated the readme to make a note of this now. I think that's all that can be done.

**Comment by ptashek** [comment]
Just wanted to add a data point from my charger, as I see this issue is still referred to in the README.

Hypervolt Home Charger 3.0 + Firmware 2627.0
The voltage value is reported, but exclusively during a charging session.

<img width="928" alt="Screenshot 2024-03-12 at 00 17 32" src="https://github.com/gndean/home-assistant-hypervolt-charger/assets/2490317/4f424f64-b530-4acf-91fc-eb08b4c66627">
